version: '3.4'
 
services:
  angulardockerapp:
    image: angular_docker_app:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 63001:4200
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    # Variables d'environnement pour la base de données
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Sportify
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
     # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1